name: Empty Commit Every 11 Hours

on:
  schedule:
    - cron: '0 */11 * * *'  # Every 11 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Automated empty commit"
          git push origin HEAD
